# Generated by Django 2.2.7 on 2020-07-07 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_mobile', models.CharField(max_length=20)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_sub', models.CharField(max_length=100)),
                ('contact_msg', models.CharField(max_length=500)),
                ('contact_status', models.CharField(default='Active', max_length=20)),
                ('contact_date', models.DateTimeField(default=datetime.datetime(2020, 7, 7, 20, 42, 28, 686252))),
            ],
        ),
    ]
