# Generated by Django 2.2.7 on 2020-07-13 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20200713_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 0, 39, 7, 629390)),
        ),
    ]
