# Generated by Django 2.2.7 on 2020-07-12 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/blog')),
                ('blog_url', models.CharField(max_length=100, unique=True)),
                ('blog_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('blog_sub_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('blog_des', models.TextField(blank=True, default=None, null=True)),
                ('blog_ex1', models.TextField(blank=True, default=None, null=True)),
                ('blog_ex2', models.TextField(blank=True, default=None, null=True)),
                ('blog_python', models.TextField(blank=True, default=None, null=True)),
                ('blog_c', models.TextField(blank=True, default=None, null=True)),
                ('blog_cpp', models.TextField(blank=True, default=None, null=True)),
                ('blog_java', models.TextField(blank=True, default=None, null=True)),
                ('blog_category', models.CharField(choices=[('advance-programming', 'ADVANCE PROGRAMMING'), ('basic-programming', 'BASIC PROGRAMMING'), ('pattern-blog', 'PATTERN BLOG')], default='ADVANCE PROGRAMMING', max_length=50)),
                ('blog_status', models.CharField(default='Active', max_length=20)),
                ('blog_date', models.DateTimeField(default=datetime.datetime(2020, 7, 13, 0, 25, 38, 214208))),
            ],
        ),
    ]
