# Generated by Django 2.2.7 on 2020-07-12 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('Advance Programming', 'ADVANCE PROGRAMMING'), ('Basic Programming', 'BASIC PROGRAMMING'), ('Pattern Blog', 'PATTERN BLOG')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 13, 0, 31, 54, 359056)),
        ),
    ]
