# Generated by Django 2.2.7 on 2020-07-13 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('learn_id', models.AutoField(primary_key=True, serialize=False)),
                ('learn_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/learn')),
                ('learn_url', models.CharField(max_length=100, unique=True)),
                ('learn_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('learn_sub_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('learn_des', models.TextField(blank=True, default=None, null=True)),
                ('learn_ex1', models.TextField(blank=True, default=None, null=True)),
                ('learn_ex2', models.TextField(blank=True, default=None, null=True)),
                ('learn_python', models.TextField(blank=True, default=None, null=True)),
                ('learn_c', models.TextField(blank=True, default=None, null=True)),
                ('learn_cpp', models.TextField(blank=True, default=None, null=True)),
                ('learn_java', models.TextField(blank=True, default=None, null=True)),
                ('learn_category', models.CharField(choices=[('Competitive Programming', 'Competitive PROGRAMMING'), ('Basic Programming', 'BASIC PROGRAMMING'), ('Pattern Programs', 'PATTERN PROGRAMS')], default='', max_length=50)),
                ('learn_status', models.CharField(default='Active', max_length=20)),
                ('learn_date', models.DateTimeField(default=datetime.datetime(2020, 7, 13, 21, 2, 5, 128047))),
            ],
        ),
    ]
