# Generated by Django 2.2.7 on 2020-07-13 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20200713_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='learn_sub_category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learn',
            name='learn_category',
            field=models.CharField(choices=[('Competitive Programming', 'COMPETITIVE PROGRAMMING'), ('Basic Programming', 'BASIC PROGRAMMING'), ('Pattern Programs', 'PATTERN PROGRAMS')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='learn',
            name='learn_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 0, 39, 7, 630351)),
        ),
        migrations.AlterField(
            model_name='learn',
            name='learn_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=20),
        ),
    ]
