# Generated by Django 2.2.7 on 2020-07-13 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20200714_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='learn_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 0, 40, 1, 498579)),
        ),
    ]
