# Generated by Django 2.2.7 on 2020-07-21 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20200714_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='learn_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 16, 43, 9, 182039)),
        ),
    ]
