# Generated by Django 2.2.7 on 2020-07-13 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolio_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/learn')),
                ('portfolio_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('portfolio_category', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('portfolio_status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Active', max_length=20)),
                ('portfolio_date', models.DateTimeField(default=datetime.datetime(2020, 7, 14, 0, 39, 7, 632345))),
            ],
        ),
    ]
