# Generated by Django 2.2.7 on 2020-07-13 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 0, 39, 51, 221996)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/portfolio'),
        ),
    ]
